name: Release and Publish Image

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/jack-turk-5/wireguard/wireguard-pro

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: podman build -t ${{ env.IMAGE_NAME }}:latest -f Containerfile

      - name: Tag and Push images to GHCR
        run: |
          LATEST_TAG="${{ env.IMAGE_NAME }}:latest"
          RELEASE_TAG="${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}"
          SHA_TAG="${{ env.IMAGE_NAME }}:${{ github.sha }}"

          podman tag "$LATEST_TAG" "$RELEASE_TAG"
          podman tag "$LATEST_TAG" "$SHA_TAG"

          podman push "$LATEST_TAG"
          podman push "$RELEASE_TAG"
          podman push "$SHA_TAG"